2023-04-22 23:05:40,957 DEBUG A DEBUG Message
2023-04-22 23:05:40,957 INFO An INFO
2023-04-22 23:05:40,957 WARNING A WARNING
2023-04-22 23:05:40,957 ERROR An ERROR
2023-04-22 23:05:40,957 CRITICAL A message of CRITICAL severity
2023-04-22 23:08:47,988 INFO The values of x and y are 3 and 4.
2023-04-22 23:08:47,988 INFO x/y successful with result: 0.75.
2023-04-22 23:08:57,664 INFO The values of x and y are 3 and 0.
2023-04-22 23:08:57,664 ERROR ZeroDivisionError
Traceback (most recent call last):
  File "D:\PyProjects\PyCharm_Big_Project\PyFiles\py_logging\logging_test.py", line 19, in <module>
    result = x / y
             ~~^~~
ZeroDivisionError: division by zero
2023-04-22 23:09:59,779 INFO The values of x and y are 3 and 0.
2023-04-22 23:09:59,779 ERROR <class 'ZeroDivisionError'>
Traceback (most recent call last):
  File "D:\PyProjects\PyCharm_Big_Project\PyFiles\py_logging\logging_test.py", line 19, in <module>
    result = x / y
             ~~^~~
ZeroDivisionError: division by zero
2023-04-22 23:10:20,389 INFO The values of x and y are 3 and 0.
2023-04-22 23:10:20,389 ERROR ZeroDivisionError
Traceback (most recent call last):
  File "D:\PyProjects\PyCharm_Big_Project\PyFiles\py_logging\logging_test.py", line 19, in <module>
    result = x / y
             ~~^~~
ZeroDivisionError: division by zero
2023-04-22 23:11:23,710 INFO The values of x and y are 3 and 0.
2023-04-22 23:11:23,710 ERROR ZeroDivisionError
Traceback (most recent call last):
  File "D:\PyProjects\PyCharm_Big_Project\PyFiles\py_logging\logging_test.py", line 19, in <module>
    result = x / y
             ~~^~~
ZeroDivisionError: division by zero
2023-04-22 23:11:47,141 INFO The values of x and y are 3 and 0.
2023-04-22 23:11:47,141 ERROR ZeroDivisionError
Traceback (most recent call last):
  File "D:\PyProjects\PyCharm_Big_Project\PyFiles\py_logging\logging_test.py", line 19, in <module>
    result = x / y
             ~~^~~
ZeroDivisionError: division by zero
2023-04-22 23:11:59,072 INFO The values of x and y are 3 and 0.
2023-04-22 23:11:59,072 ERROR ZeroDivisionError
2023-04-22 23:19:15,501 INFO The values of x and y are 2 and 5.
2023-04-22 23:19:15,501 INFO x/y successful with result: 0.4.
2023-04-22 23:19:15,501 INFO The values of x and y are 3 and 7.
2023-04-22 23:19:15,501 INFO x/y successful with result: 0.42857142857142855.
2023-04-22 23:19:15,501 INFO The values of x and y are 6 and 12.
2023-04-22 23:19:15,501 INFO x/y successful with result: 0.5.
2023-04-22 23:19:15,501 INFO The values of x and y are 4 and 0.
2023-04-22 23:19:15,501 ERROR ZeroDivisionError
Traceback (most recent call last):
  File "D:\PyProjects\PyCharm_Big_Project\PyFiles\py_logging\logging_test.py", line 31, in <module>
    result = x / y
             ~~^~~
ZeroDivisionError: division by zero
2023-04-22 23:19:15,503 INFO The values of x and y are 10 and 1.
2023-04-22 23:19:15,503 INFO x/y successful with result: 10.0.
2023-04-22 23:19:54,887 DEBUG A DEBUG Message
2023-04-22 23:19:54,887 INFO An INFO
2023-04-22 23:19:54,887 WARNING A WARNING
2023-04-22 23:19:54,887 ERROR An ERROR
2023-04-22 23:19:54,887 CRITICAL A message of CRITICAL severity
2023-04-22 23:19:54,887 INFO The values of x and y are 3 and 0.
2023-04-22 23:19:54,887 ERROR ZeroDivisionError
Traceback (most recent call last):
  File "D:\PyProjects\PyCharm_Big_Project\PyFiles\py_logging\logging_test.py", line 22, in <module>
    result = x / y
             ~~^~~
ZeroDivisionError: division by zero
